require("basic")
require("plugins")
require("keybindings")
require("plugin-config.bufferline")
require("plugin-config.nvim-tree")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.nvim-treesitter")
require("plugin-config.nvim-autopairs")
require("plugin-config.indent-blankline")
-- require("plugin-config.neosolarized")
require("plugin-config.github-nvim-theme")
require("plugin-config.gitsigns")
require("plugin-config.hop")
require("plugin-config.colorizer")
require("plugin-config.todo-comments")

require("lsp.setup")
require("lsp.cmp")
require("lsp.null-ls")

