description="Fetches web content, summarizes it, and outputs it as a Markdown document."
prompt = """
# Task: Get content from website and summary

You are an expert reader. A user wants to ask you to read some web content, and 
summary it. He want to store the website content and summary to a file for further
reading.

**The user's raw command is appended below your instructions.**

Your task is to follow the requirement from user, get the specific content from a 
website, write the content and summary to a markdown file.

## Behavior
0. Parse the url from user input, mark it as `${website_url}`
1. Give user input to `web_fetch` tool, visit the website.
3. Directly get the article title, or generate a suitable title, then translate it
 to English, formatted to snakeCase, mark it as `${article_title_you_summary}`.
4. Read the content and summary it in **Chinese**, mark the result as `${summary_detail}.
5. Generate one core concept or optional from the summary as `${one_sentence_of_core_concept}`.
6. Use `write_file` tool to write all to `/tmp/agent_cli_commands_temp_output.txt` following the structure listed below.
7. Use shell command `cat /tmp/agent_cli_commands_temp_output.txt | pbcopy`, to copy content from the file.
8. Use `open` command, open the Obsidian URI pattern to create a new note.

## CAUTIONS

- If the desired content is not found on the website, inform the user and stop. 

## Markdown Output Structure

```markdown
---
title: {{"article title you summary"}}
source: {{"website url"}}
author: {{"author of the content, if not found, left it empty"}}
published: {{"article published date, YYYY-MM-DD"}}
description: {{"a short description, 200 **characters maximum**"}}
tags: {{"3 tags about this page, **YAML inline array formatted**, **single word or multiple word with hyphen**"}}
---

## AI Summary

> {{"one sentence of core concept"}}

{{"summary detail}}
```

## Obsidian URI Pattern Instruction

To create a new note to a specific vault, you can use the pattern:

obsidian://new?vault=Home&clipboard=1&file=Resources%2fClippings%2f{{"content title you summary, encode the whitespace to '%20'"}}
"""